BEGIN;

ALTER TABLE IF EXISTS public."WeeklyAnalytics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Post" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Author" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Tag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Comment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."AnalyticsData" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ChatSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ContactLead" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."NewsletterSubscriber" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Clinic" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ChatMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."GMBConnection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."GMBData" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."_PostTags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."_PostCategories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ClientClinic" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."AiHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."GoogleApiCache" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."WeeklyOngoingTask" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."WeeklyOngoingSnapshot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."GA4Data" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SearchConsoleData" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."NewsArticle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."GoogleAdsData" ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public."SiteKnowledge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."UnansweredQuestion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."MonthlyClinicReportEmail" ENABLE ROW LEVEL SECURITY;

COMMIT;