export interface IndustryData {
  slug: string;
  title: string;
  metaDescription: string;
  h1: string;
  heroDescription: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  accentColor: string;       // tailwind color class stem, e.g. 'red' 'blue' 'emerald'
  icon: string;              // emoji
  challenges: { title: string; description: string }[];
  services: { slug: string; label: string }[];
  whyUs: { title: string; description: string }[];
  stats: { value: string; label: string }[];
  faqs: { q: string; a: string }[];
  relatedIndustries: { slug: string; label: string }[];
}

export const industries: IndustryData[] = [
  {
    slug: 'dental',
    title: 'Dental Marketing Agency — Grow Your Dental Practice | NextGen Health',
    metaDescription: 'Specialist dental marketing: SEO, Google Ads, social media & website design for dental clinics. More patients, more revenue.',
    h1: 'Dental Marketing — Grow Your Dental Practice',
    heroDescription: 'Attract more patients, dominate local search, and build a recognisable dental brand. We create marketing strategies tailored to the unique challenges of dental practices.',
    primaryKeyword: 'dental marketing agency',
    secondaryKeywords: ['dental SEO', 'dental clinic marketing', 'marketing for dentists', 'dental practice growth'],
    accentColor: 'sky',
    icon: '🦷',
    challenges: [
      { title: 'Corporate Dental Chain Competition', description: 'Large chains outspend solo and group practices on ads and brand awareness, making it hard to compete on visibility alone.' },
      { title: 'Local Search Visibility', description: "If your clinic isn't in Google's Local Pack for \"dentist near me,\" you're invisible to 70% of new patients searching online." },
      { title: 'Patient Trust & Reviews', description: 'Dental anxiety is real. Patients read dozens of reviews before choosing a dentist — your online reputation makes or breaks your practice.' },
      { title: 'New Patient Acquisition Cost', description: 'Rising ad costs mean you need smarter campaigns that target high-intent keywords and convert at higher rates.' },
      { title: 'Retention & Recall', description: 'Most dental practices lose 15-20% of patients annually. Automated recall systems keep your hygiene schedule full.' },
    ],
    services: [
      { slug: 'seo-local-search', label: 'SEO & Local Search' },
      { slug: 'google-ads', label: 'Google Ads' },
      { slug: 'social-media-marketing', label: 'Social Media Marketing' },
      { slug: 'google-business-profile', label: 'Google Business Profile' },
      { slug: 'website-design-dev', label: 'Website Design' },
      { slug: 'content-copywriting', label: 'Content & Copywriting' },
    ],
    whyUs: [
      { title: 'Dental-Specific Keyword Strategy', description: 'We know the exact search terms patients use — from "emergency dentist" to "Invisalign near me" — and target them precisely.' },
      { title: 'HIPAA-Compliant Campaigns', description: 'Every ad, form, and automation we build meets HIPAA standards, protecting your practice and your patients.' },
      { title: 'Review Generation Systems', description: 'Automated post-visit workflows that drive positive Google reviews consistently, building a 4.8+ star reputation.' },
      { title: 'Multi-Location Expertise', description: 'We manage marketing for multi-location dental groups with location-specific strategies for each office.' },
    ],
    stats: [
      { value: '340%', label: 'Average organic traffic increase' },
      { value: '45+', label: 'New patients/month per location' },
      { value: '4.8★', label: 'Average Google rating achieved' },
      { value: '$18', label: 'Average cost per new patient lead' },
    ],
    faqs: [
      { q: 'How much does dental marketing cost?', a: 'Our dental marketing packages typically range from $2,500 to $7,500 per month depending on your goals, location count, and competitive landscape. We always start with a free strategy session to recommend the right investment level for your practice.' },
      { q: 'How long until I see more dental patients?', a: 'Google Ads can generate new patient enquiries within the first week. SEO results typically start showing in 60-90 days, with significant patient volume increases by month 4-6. We provide transparent monthly reporting so you can track progress.' },
      { q: 'What are the best marketing channels for dentists?', a: 'For most dental practices, the highest-ROI combination is Google Ads (for immediate leads) + SEO & Google Business Profile (for long-term organic growth) + automated review management. Social media is excellent for cosmetic dentistry and practice branding.' },
      { q: 'Do you work with dental DSOs and group practices?', a: 'Yes. We have experience with single-location practices through multi-location dental groups and DSOs. For larger organisations, we provide centralised campaign management with location-specific optimisation.' },
      { q: 'Can you help with cosmetic dentistry marketing?', a: 'Absolutely. Cosmetic dentistry (veneers, Invisalign, whitening) requires a visual, aspirational marketing approach. We use before/after content (within compliance), Instagram/Facebook campaigns, and dedicated landing pages to attract high-value cosmetic patients.' },
    ],
    relatedIndustries: [
      { slug: 'medspa', label: 'Medspa Marketing' },
      { slug: 'primary-care', label: 'Primary Care Marketing' },
      { slug: 'chiropractic', label: 'Chiropractic Marketing' },
    ],
  },
  {
    slug: 'urgent-care',
    title: 'Urgent Care Marketing — Attract Walk-In Patients | NextGen Health',
    metaDescription: 'Urgent care marketing strategies that drive walk-in patients. Google Ads, local SEO, and automation for urgent care clinics.',
    h1: 'Urgent Care Marketing — Fill Your Clinic Every Day',
    heroDescription: 'Drive walk-in patient volume with targeted Google Ads, local SEO dominance, and automated patient communication. Our strategies are built for the fast-paced urgent care model.',
    primaryKeyword: 'urgent care marketing',
    secondaryKeywords: ['urgent care advertising', 'how to market urgent care', 'urgent care patient acquisition'],
    accentColor: 'blue',
    icon: '🏥',
    challenges: [
      { title: 'ER & Telehealth Competition', description: 'Freestanding ERs capture high-acuity patients while telehealth siphons minor illness visits. You need to own the middle ground.' },
      { title: 'Location-Based Search', description: 'Urgent care is hyper-local. If you don\'t rank in the Local Pack within a 5-mile radius, patients drive to a competitor.' },
      { title: 'Seasonal Demand Fluctuations', description: 'Flu season spikes and summer slowdowns require agile marketing budgets and campaigns that adapt in real time.' },
      { title: 'Insurance Visibility', description: 'Patients filter by accepted insurance. Your marketing must prominently display accepted plans to avoid lost clicks.' },
      { title: 'Wait Time Perception', description: 'Long perceived wait times kill urgent care businesses. Marketing transparency on wait times builds trust.' },
    ],
    services: [
      { slug: 'google-ads', label: 'Google Ads' },
      { slug: 'seo-local-search', label: 'SEO & Local Search' },
      { slug: 'google-business-profile', label: 'Google Business Profile' },
      { slug: 'on-site-field-marketing', label: 'On-Site Field Marketing' },
      { slug: 'analytics-reporting', label: 'Analytics & Reporting' },
    ],
    whyUs: [
      { title: 'Urgent Care Ad Specialists', description: 'We manage urgent care Google Ads campaigns optimised for walk-in conversions, not just clicks.' },
      { title: 'Real-Time Wait Time Integration', description: 'We integrate live wait time data into your GBP and ads to attract convenience-driven patients.' },
      { title: 'Multi-Location Scaling', description: 'Whether you have 1 or 50 locations, we build scalable campaigns with location-specific optimisation.' },
      { title: 'Field Marketing Expertise', description: 'Our on-site teams drive community awareness with events, partnerships, and direct outreach.' },
    ],
    stats: [
      { value: '52%', label: 'Increase in walk-in volume' },
      { value: '$12', label: 'Average cost per walk-in patient' },
      { value: '#1', label: 'Local Pack ranking achieved' },
      { value: '180+', label: 'New patients/week per location' },
    ],
    faqs: [
      { q: 'How do I get more walk-in patients?', a: 'The fastest path is Google Ads targeting symptom-based keywords ("flu test near me", "sprained ankle urgent care") combined with an optimised Google Business Profile showing your hours, wait times, and reviews. We typically see 30-50% more walk-ins within 30 days of campaign launch.' },
      { q: 'What is the best advertising for urgent care?', a: 'Google Ads (Search + Local Services Ads) is the #1 channel for urgent care because patients are actively searching when they need care. We supplement with Meta Ads for brand awareness and geofencing around competitor locations.' },
      { q: 'How do we compete with ERs for patients?', a: 'Educate patients on what conditions you treat, emphasise shorter wait times and lower costs, and dominate "urgent care near me" keywords. We create comparison content and ads that position your clinic as the smart choice for non-emergency conditions.' },
      { q: 'How do you handle seasonal marketing changes?', a: 'We build dynamic campaigns that scale budgets and messaging with seasonal demand — ramping up flu-season keywords in autumn and allergy terms in spring. Monthly strategy reviews ensure your spend is always optimised.' },
    ],
    relatedIndustries: [
      { slug: 'freestanding-ers', label: 'Freestanding ER Marketing' },
      { slug: 'primary-care', label: 'Primary Care Marketing' },
      { slug: 'chiropractic', label: 'Chiropractic Marketing' },
    ],
  },
  {
    slug: 'medspa',
    title: 'Medspa Marketing — Attract Aesthetic Patients | NextGen Health',
    metaDescription: 'Medspa marketing that fills your appointment book. Social media, Google Ads, and SEO for medical spas and aesthetic practices.',
    h1: 'Medspa Marketing — Attract More Aesthetic Patients',
    heroDescription: 'Fill your appointment book with high-value aesthetic patients. Our social-first, visually-driven marketing strategies are built for the unique demands of medical spas.',
    primaryKeyword: 'medspa marketing',
    secondaryKeywords: ['medical spa advertising', 'aesthetic practice marketing', 'medspa SEO'],
    accentColor: 'pink',
    icon: '✨',
    challenges: [
      { title: 'Visual-First Audience', description: 'Medspa patients are driven by before/after results. Your marketing must be visually stunning and aspirational.' },
      { title: 'Social Media Dependency', description: 'Instagram and TikTok are primary discovery channels. Inconsistent posting means invisibility to your ideal patient.' },
      { title: 'Before/After Compliance', description: 'Sharing before/after photos has advertising regulations. Your marketing must comply with state medical board rules and platform policies.' },
      { title: 'High Local Competition', description: 'Medspa density is rising fast. Standing out requires a brand identity that communicates luxury, trust, and expertise.' },
      { title: 'Seasonal Promotion Management', description: 'Holiday specials, summer body campaigns, and new treatment launches require an agile marketing calendar.' },
    ],
    services: [
      { slug: 'social-media-marketing', label: 'Social Media Marketing' },
      { slug: 'meta-ads', label: 'Meta (Facebook/Instagram) Ads' },
      { slug: 'website-design-dev', label: 'Website Design' },
      { slug: 'content-copywriting', label: 'Content & Copywriting' },
      { slug: 'brand-identity-design', label: 'Brand Identity Design' },
      { slug: 'seo-local-search', label: 'SEO & Local Search' },
    ],
    whyUs: [
      { title: 'Aesthetic-Industry Experience', description: 'We understand the visual, aspirational nature of medspa marketing and build campaigns that convert scrollers into bookings.' },
      { title: 'Compliant Content Creation', description: 'We know the rules around before/after imagery and treatment claims, ensuring your content is effective AND compliant.' },
      { title: 'Social Media Mastery', description: 'Consistent, on-brand Instagram and Facebook content that builds a loyal following and drives DM enquiries.' },
      { title: 'Luxury Brand Positioning', description: 'We position your medspa as a premium destination, justifying higher price points through sophisticated branding.' },
    ],
    stats: [
      { value: '280%', label: 'Social media engagement increase' },
      { value: '$35', label: 'Average cost per booking lead' },
      { value: '60%', label: 'Increase in monthly bookings' },
      { value: '12K+', label: 'Instagram followers grown' },
    ],
    faqs: [
      { q: 'What is the best social media platform for medspas?', a: 'Instagram is the #1 platform for medspas due to its visual nature. We also leverage Facebook for targeted ads (especially for 35+ demographics), TikTok for viral reach, and Google for capturing high-intent search traffic. A multi-platform strategy delivers the best results.' },
      { q: 'How do I advertise Botox and fillers legally?', a: 'Each state has specific regulations. Generally, you must avoid misleading claims, include proper disclaimers, and follow platform-specific policies (Meta restricts certain targeting for health-related ads). We build compliant campaigns that maximise reach within these boundaries.' },
      { q: 'How do I get more medspa bookings?', a: 'The fastest approach combines Meta Ads with compelling before/after content, an optimised booking page, and automated follow-up sequences. We typically increase bookings by 40-60% within the first 90 days by optimising the full patient journey from ad click to appointment.' },
      { q: 'How much should a medspa spend on marketing?', a: 'A general benchmark is 10-15% of revenue for growth-stage medspas and 5-8% for established practices. For a medspa generating $50K/month, that translates to $5,000-$7,500 in marketing investment. We help you allocate budgets across channels for maximum ROI.' },
    ],
    relatedIndustries: [
      { slug: 'plastic-surgery', label: 'Plastic Surgery Marketing' },
      { slug: 'dermatology', label: 'Dermatology Marketing' },
      { slug: 'dental', label: 'Dental Marketing' },
    ],
  },
  {
    slug: 'freestanding-ers',
    title: 'Freestanding ER Marketing — Stand Out in Your Market | NextGen Health',
    metaDescription: 'Marketing for freestanding emergency rooms. Google Ads, local SEO, and community outreach to drive ER patient volume.',
    h1: 'Freestanding ER Marketing — Build Community Trust',
    heroDescription: 'Drive patient volume and build community trust for your freestanding ER. We specialise in high-acuity patient acquisition through Google Ads, local SEO, and strategic community outreach.',
    primaryKeyword: 'freestanding ER marketing',
    secondaryKeywords: ['free-standing emergency room advertising', 'ER marketing', 'emergency room patient acquisition'],
    accentColor: 'red',
    icon: '🚑',
    challenges: [
      { title: 'Urgent Care Confusion', description: 'Most patients don\'t understand the difference between an ER and urgent care. Your marketing must educate while promoting.' },
      { title: 'Community Trust Building', description: 'Freestanding ERs are newer concepts in many markets. Building trust requires consistent community presence and education.' },
      { title: '"ER vs Urgent Care" Education', description: 'Patients searching for care need to understand when an ER is the right choice. Content marketing bridges this knowledge gap.' },
      { title: 'Grand Opening Campaigns', description: 'New ER openings need aggressive, multi-channel launch campaigns to build awareness quickly in the local community.' },
      { title: 'Insurance Network Visibility', description: 'ER billing concerns deter patients. Marketing must clearly communicate accepted insurance and pricing transparency.' },
    ],
    services: [
      { slug: 'google-ads', label: 'Google Ads' },
      { slug: 'seo-local-search', label: 'SEO & Local Search' },
      { slug: 'google-business-profile', label: 'Google Business Profile' },
      { slug: 'on-site-field-marketing', label: 'On-Site Field Marketing' },
      { slug: 'brand-identity-design', label: 'Brand Identity Design' },
    ],
    whyUs: [
      { title: 'ER Launch Specialists', description: 'We\'ve launched multiple freestanding ERs with grand opening campaigns that generate 1,000+ community engagements in week one.' },
      { title: 'High-Acuity Keyword Mastery', description: 'We target the exact symptoms and conditions that drive ER visits — "chest pain near me", "broken bone emergency" — with precision bidding.' },
      { title: 'Competitor Geofencing', description: 'We serve targeted ads to patients near competing urgent cares and ERs, capturing overflow and higher-acuity cases.' },
      { title: 'Community Outreach Programs', description: 'Our field marketing team builds relationships with local businesses, schools, and organisations to drive awareness.' },
    ],
    stats: [
      { value: '1,200+', label: 'Grand opening event attendees' },
      { value: '#1', label: 'Local Pack ranking for ER keywords' },
      { value: '65%', label: 'Increase in patient volume' },
      { value: '$22', label: 'Average cost per ER patient lead' },
    ],
    faqs: [
      { q: 'How do I differentiate from urgent care in marketing?', a: 'Focus on capabilities urgent cares lack: 24/7 availability, on-site imaging (CT, X-ray), board-certified emergency physicians, and the ability to handle life-threatening emergencies. We build comparison content, educational videos, and targeted ads that clearly communicate your ER-level capabilities.' },
      { q: 'What is the best advertising for a new ER opening?', a: 'A multi-phase approach: 1) Pre-launch awareness with social media and community events, 2) Grand opening blitz with Google Ads, geofencing, and field marketing, 3) Sustained growth with SEO and reputation building. We typically recommend a 6-month launch marketing budget.' },
      { q: 'How do I build trust for a freestanding ER?', a: 'Trust comes from visibility and education. We build this through Google Business Profile optimisation with extensive photos, community event sponsorships, educational content about ER capabilities, and a strong review generation system. Consistent 5-star reviews are the fastest trust signal.' },
      { q: 'How do freestanding ER marketing costs compare?', a: 'ER patient acquisition costs are higher than urgent care ($20-40 per lead vs $8-15) but the revenue per patient is significantly higher. With the right targeting, ROAS is typically 5-8x for well-managed ER campaigns.' },
    ],
    relatedIndustries: [
      { slug: 'urgent-care', label: 'Urgent Care Marketing' },
      { slug: 'primary-care', label: 'Primary Care Marketing' },
      { slug: 'mental-health', label: 'Mental Health Marketing' },
    ],
  },
  {
    slug: 'mental-health',
    title: 'Mental Health Practice Marketing | NextGen Health',
    metaDescription: 'Sensitive, effective marketing for mental health practices. SEO, content, and HIPAA-compliant strategies to reach patients in need.',
    h1: 'Mental Health Practice Marketing — Reach Patients Sensitively',
    heroDescription: 'Connect with patients who need help, sensitively and effectively. Our HIPAA-compliant marketing strategies help therapists, counsellors, and psychiatrists grow their practices while maintaining ethical standards.',
    primaryKeyword: 'mental health practice marketing',
    secondaryKeywords: ['therapist marketing', 'counselling practice marketing', 'mental health SEO'],
    accentColor: 'purple',
    icon: '🧠',
    challenges: [
      { title: 'Stigma Sensitivity', description: 'Mental health marketing must be compassionate and destigmatising. Tone-deaf messaging can cause harm and damage your reputation.' },
      { title: 'Strict HIPAA Requirements', description: 'Mental health data is among the most sensitive. Every marketing touchpoint must be fully HIPAA-compliant.' },
      { title: 'Trust-First Patient Journey', description: 'Patients seeking therapy research extensively before booking. Your content must build trust over multiple touchpoints.' },
      { title: 'Telehealth Integration', description: 'Many patients prefer virtual visits. Your marketing must promote both in-person and telehealth options seamlessly.' },
      { title: 'Insurance vs. Self-Pay Mix', description: 'Communicating insurance acceptance and self-pay options clearly affects patient acquisition and practice economics.' },
    ],
    services: [
      { slug: 'seo-local-search', label: 'SEO & Local Search' },
      { slug: 'content-copywriting', label: 'Content & Copywriting' },
      { slug: 'email-drip-campaigns', label: 'Email Campaigns' },
      { slug: 'website-design-dev', label: 'Website Design' },
      { slug: 'analytics-reporting', label: 'Analytics & Reporting' },
    ],
    whyUs: [
      { title: 'Sensitive Messaging Expertise', description: 'We craft compassionate, destigmatising marketing that resonates with patients in need without being exploitative.' },
      { title: 'Full HIPAA Compliance', description: 'Every form, ad, chatbot, and automation we build adheres to HIPAA and state-specific mental health privacy regulations.' },
      { title: 'Educational Content Strategy', description: 'Long-form blog content and resource pages that build authority and attract patients through organic search.' },
      { title: 'Telehealth Marketing', description: 'We promote your virtual services to expand your reach beyond your immediate geographic area.' },
    ],
    stats: [
      { value: '210%', label: 'Increase in organic enquiries' },
      { value: '85%', label: 'Of leads from content marketing' },
      { value: '4.9★', label: 'Average therapist profile rating' },
      { value: '$25', label: 'Average cost per qualified lead' },
    ],
    faqs: [
      { q: 'How do I market a therapy practice ethically?', a: 'Focus on education, not fear. Create content that normalises seeking help, provides value (coping strategies, mental health resources), and positions your practice as a safe, welcoming environment. Avoid language that could be perceived as exploiting vulnerability. We specialise in this balance.' },
      { q: 'Is mental health advertising HIPAA-compliant?', a: 'It can be — when done correctly. The key is never using patient data for targeting, ensuring all forms and communications are encrypted, and having BAAs with all marketing technology providers. We audit every campaign for HIPAA compliance before launch.' },
      { q: 'What are the best marketing channels for therapists?', a: 'SEO and content marketing drive the highest-quality leads because patients actively search for help. Google Ads captures high-intent searches. Social media (especially Instagram) builds community and reduces stigma. We recommend a content-first strategy supplemented with targeted ads.' },
      { q: 'How do I market telehealth therapy services?', a: 'Highlight convenience, privacy, and accessibility in your messaging. Create dedicated telehealth landing pages optimised for "online therapy" keywords. Expand your geo-targeting beyond your physical location to reach patients statewide (where licensure allows).' },
    ],
    relatedIndustries: [
      { slug: 'primary-care', label: 'Primary Care Marketing' },
      { slug: 'chiropractic', label: 'Chiropractic Marketing' },
      { slug: 'dental', label: 'Dental Marketing' },
    ],
  },
  {
    slug: 'primary-care',
    title: 'Primary Care Marketing — Grow Your Patient Panel | NextGen Health',
    metaDescription: 'Primary care marketing that builds your patient panel. SEO, Google Ads, and patient retention strategies for family practices.',
    h1: 'Primary Care Marketing — Build a Loyal Patient Panel',
    heroDescription: 'Grow and retain your patient panel with strategies designed for family practices and primary care physicians. From new patient acquisition to recall campaigns, we help you build a thriving practice.',
    primaryKeyword: 'primary care marketing',
    secondaryKeywords: ['family practice marketing', 'GP marketing', 'patient panel growth'],
    accentColor: 'teal',
    icon: '👨‍⚕️',
    challenges: [
      { title: 'Insurance Panel Dynamics', description: 'Accepted insurance networks significantly impact patient choice. Your marketing must clearly communicate your panel participation.' },
      { title: 'Patient Retention & Loyalty', description: 'Retaining patients long-term is essential for primary care economics. Recall systems and ongoing communication prevent attrition.' },
      { title: 'Retail Clinic Competition', description: 'CVS MinuteClinics, Walmart Health, and other retail options erode traditional primary care patient bases.' },
      { title: 'Telehealth Encroachment', description: 'Direct-to-consumer telehealth companies attract younger demographics who prioritise convenience over continuity of care.' },
      { title: 'New Patient Onboarding', description: 'The first visit experience determines retention. Marketing sets expectations; operations must deliver.' },
    ],
    services: [
      { slug: 'seo-local-search', label: 'SEO & Local Search' },
      { slug: 'google-business-profile', label: 'Google Business Profile' },
      { slug: 'email-drip-campaigns', label: 'Email Campaigns' },
      { slug: 'analytics-reporting', label: 'Analytics & Reporting' },
      { slug: 'website-design-dev', label: 'Website Design' },
    ],
    whyUs: [
      { title: 'Patient Lifecycle Marketing', description: 'We market across the entire patient journey — from acquisition to onboarding to retention and recall.' },
      { title: 'Recall Campaign Automation', description: 'Automated email and SMS sequences that bring patients back for annual physicals, vaccinations, and follow-ups.' },
      { title: 'Insurance Messaging Strategy', description: 'We ensure your accepted insurance networks are prominently displayed across all digital touchpoints.' },
      { title: 'Community-First Approach', description: 'Primary care is about relationships. Our marketing builds community trust through educational content and local engagement.' },
    ],
    stats: [
      { value: '38%', label: 'Increase in new patient enrolments' },
      { value: '92%', label: 'Patient retention rate achieved' },
      { value: '25%', label: 'Reduction in no-shows' },
      { value: '$15', label: 'Average cost per new patient' },
    ],
    faqs: [
      { q: 'How do I attract new patients to a primary care practice?', a: 'A combination of Google Business Profile optimisation (ranking in "family doctor near me" searches), SEO for condition-specific keywords, and Google Ads for immediate visibility. We also build referral programs and community partnerships to drive word-of-mouth growth.' },
      { q: 'How do I reduce patient attrition?', a: 'Automated recall campaigns are the #1 tool. We set up email and SMS workflows that remind patients about annual physicals, flu shots, and follow-up appointments. Combined with a patient satisfaction feedback loop, most practices see 15-25% improvement in retention.' },
      { q: 'What is the best marketing for family practices?', a: 'For family practices, local SEO + Google Business Profile is the foundation. Add a patient-friendly website with online scheduling, automated appointment reminders, and a steady stream of health education blog content. This combination builds trust and drives consistent new patient flow.' },
      { q: 'How do I compete with retail clinics?', a: 'Emphasise what retail clinics cannot offer: continuity of care, personal relationships with a dedicated physician, comprehensive health management, and coordination of specialist referrals. Position your practice as the long-term health partner versus a transactional visit.' },
    ],
    relatedIndustries: [
      { slug: 'urgent-care', label: 'Urgent Care Marketing' },
      { slug: 'mental-health', label: 'Mental Health Marketing' },
      { slug: 'chiropractic', label: 'Chiropractic Marketing' },
    ],
  },
  {
    slug: 'chiropractic',
    title: 'Chiropractic Marketing — More Patients, More Adjustments | NextGen Health',
    metaDescription: 'Chiropractic marketing that fills your schedule. SEO, Google Ads, and social media for chiropractors.',
    h1: 'Chiropractic Marketing — Grow Your Practice',
    heroDescription: 'Fill your adjustment schedule with new and returning patients. Our marketing strategies are designed for the unique challenges of chiropractic practices, from patient education to local search dominance.',
    primaryKeyword: 'chiropractic marketing',
    secondaryKeywords: ['chiropractor advertising', 'chiropractic SEO', 'marketing for chiropractors'],
    accentColor: 'orange',
    icon: '🦴',
    challenges: [
      { title: 'Patient Education Gap', description: 'Many potential patients don\'t understand the benefits of chiropractic care. Educational marketing bridges this gap and drives new patient interest.' },
      { title: 'Referral-Dependent Growth', description: 'Over-reliance on word-of-mouth limits growth. Digital marketing creates a predictable new patient pipeline.' },
      { title: 'Local Competition', description: 'Chiropractic markets are competitive. Differentiating your practice requires strong branding and local search visibility.' },
      { title: 'Appointment Frequency', description: 'Chiropractic care requires multiple visits. Marketing must set treatment plan expectations and reduce early drop-off.' },
      { title: 'Insurance vs. Cash Pay', description: 'Communicating insurance acceptance and the value of out-of-pocket chiropractic care affects patient acquisition.' },
    ],
    services: [
      { slug: 'seo-local-search', label: 'SEO & Local Search' },
      { slug: 'google-ads', label: 'Google Ads' },
      { slug: 'social-media-marketing', label: 'Social Media Marketing' },
      { slug: 'content-copywriting', label: 'Content & Copywriting' },
      { slug: 'google-business-profile', label: 'Google Business Profile' },
    ],
    whyUs: [
      { title: 'Chiropractic Content Expertise', description: 'We create educational content that explains chiropractic benefits, addresses common concerns, and drives appointment bookings.' },
      { title: 'New Patient Special Campaigns', description: 'Strategic "new patient special" offers promoted through Google Ads and social media that generate high-quality leads.' },
      { title: 'Review & Reputation Focus', description: 'Automated review collection that builds a 4.8+ star rating — critical for chiropractic practices where trust is paramount.' },
      { title: 'Treatment Plan Retention', description: 'Automated appointment reminders and educational drip sequences that keep patients committed to their treatment plans.' },
    ],
    stats: [
      { value: '48', label: 'New patients per month average' },
      { value: '300%', label: 'Increase in website traffic' },
      { value: '$20', label: 'Cost per new patient lead' },
      { value: '4.9★', label: 'Average Google rating achieved' },
    ],
    faqs: [
      { q: 'How do I get more chiropractic patients?', a: 'Google Ads targeting "chiropractor near me" and condition-specific searches (back pain, sciatica, neck pain) generates immediate leads. Long-term, SEO and content marketing build organic visibility. We also implement referral incentive programs and community wellness events.' },
      { q: 'What social media works best for chiropractors?', a: 'Instagram and Facebook are most effective. Short-form video content (adjustment clips, patient testimonials, educational tips) performs exceptionally well. We create content calendars and manage posting to keep your practice visible and engaged.' },
      { q: 'How do I educate patients about chiropractic care?', a: 'Blog content, video explainers, and social media posts that address common conditions (back pain, headaches, posture) and explain how chiropractic care helps. This content ranks in Google, builds trust, and positions you as an authority.' },
      { q: 'Should I offer a new patient special?', a: 'Yes — strategically. A compelling first-visit offer ($49 initial exam, free consultation) promoted through Google Ads reduces the barrier to entry. The key is converting these promotions into long-term treatment plan patients through excellent care and automated follow-up.' },
    ],
    relatedIndustries: [
      { slug: 'primary-care', label: 'Primary Care Marketing' },
      { slug: 'dental', label: 'Dental Marketing' },
      { slug: 'mental-health', label: 'Mental Health Marketing' },
    ],
  },
  {
    slug: 'plastic-surgery',
    title: 'Plastic Surgery Marketing — High-Value Patient Acquisition | NextGen Health',
    metaDescription: 'Digital marketing for plastic surgeons. Google Ads, SEO, and social media to attract high-value cosmetic surgery patients.',
    h1: 'Plastic Surgery Marketing — Attract High-Value Patients',
    heroDescription: 'Attract affluent, high-value cosmetic surgery patients with sophisticated digital marketing. Our strategies combine visual storytelling, premium branding, and precision targeting.',
    primaryKeyword: 'plastic surgery marketing',
    secondaryKeywords: ['cosmetic surgery advertising', 'plastic surgeon SEO', 'plastic surgery digital marketing'],
    accentColor: 'rose',
    icon: '💎',
    challenges: [
      { title: 'High Patient Value, High Stakes', description: 'Cosmetic surgery patients invest $5K-$50K+ per procedure. Your marketing must convey expertise, safety, and premium quality.' },
      { title: 'Visual-First Decision Making', description: 'Patients judge surgeons by before/after galleries. Your visual content must be exceptional and compliant with regulations.' },
      { title: 'Before/After Compliance', description: 'Advertising regulations around cosmetic surgery imagery vary by state. Non-compliance risks fines and licence issues.' },
      { title: 'Reputation is Everything', description: 'One negative review about a surgical outcome can devastate your practice. Proactive reputation management is essential.' },
      { title: 'Long Sales Cycle', description: 'Cosmetic surgery decisions take weeks to months. Your marketing must nurture leads through the entire consideration journey.' },
    ],
    services: [
      { slug: 'google-ads', label: 'Google Ads' },
      { slug: 'seo-local-search', label: 'SEO & Local Search' },
      { slug: 'social-media-marketing', label: 'Social Media Marketing' },
      { slug: 'website-design-dev', label: 'Website Design' },
      { slug: 'brand-identity-design', label: 'Brand Identity Design' },
      { slug: 'meta-ads', label: 'Meta Ads' },
    ],
    whyUs: [
      { title: 'Premium Brand Positioning', description: 'We position your practice as the premier surgical destination, justifying premium pricing and attracting affluent patients.' },
      { title: 'Compliant Visual Strategy', description: 'Expert management of before/after galleries, patient testimonials, and procedure imagery within all regulatory guidelines.' },
      { title: 'Lead Nurture Sequences', description: 'Automated email and SMS workflows that educate and nurture prospective patients from initial enquiry to consultation booking.' },
      { title: 'High-Ticket Ad Management', description: 'Google and Meta Ads campaigns optimised for consultation bookings, not just clicks — targeting patients ready to invest.' },
    ],
    stats: [
      { value: '8.5x', label: 'Average return on ad spend' },
      { value: '$85', label: 'Cost per consultation lead' },
      { value: '45%', label: 'Lead-to-consultation rate' },
      { value: '320%', label: 'Organic traffic increase' },
    ],
    faqs: [
      { q: 'How do I attract more cosmetic surgery patients?', a: 'A multi-channel approach: Google Ads for high-intent searches ("rhinoplasty near me"), Instagram/TikTok for visual storytelling, SEO for procedure-specific content, and automated nurture sequences to convert consultations. Premium website design is also critical for first impressions.' },
      { q: 'How much should a plastic surgeon spend on marketing?', a: 'Most successful plastic surgery practices invest 8-12% of revenue in marketing. For a practice generating $2M annually, that\'s $160K-$240K. The high patient value (average $8K+ per procedure) means even a modest improvement in lead quality delivers significant ROI.' },
      { q: 'How do I handle negative reviews?', a: 'Proactive review management is key: generate a steady flow of positive reviews to dilute any negatives, respond professionally to all feedback, and implement a satisfaction survey before patients leave to catch issues early. We set up automated systems that handle this entire process.' },
      { q: 'Is social media important for plastic surgeons?', a: 'Extremely. Instagram is where prospective patients discover surgeons and evaluate results. Before/after Reels, patient journey stories, and educational content drive significant consultation bookings. We create and manage content strategies specifically designed for surgical practices.' },
    ],
    relatedIndustries: [
      { slug: 'medspa', label: 'Medspa Marketing' },
      { slug: 'dermatology', label: 'Dermatology Marketing' },
      { slug: 'ophthalmology', label: 'Ophthalmology Marketing' },
    ],
  },
  {
    slug: 'ophthalmology',
    title: 'Ophthalmology Marketing — Grow Your Eye Care Practice | NextGen Health',
    metaDescription: 'Marketing for ophthalmologists and eye care practices. SEO, Google Ads, and patient communication strategies.',
    h1: 'Ophthalmology Marketing — Grow Your Eye Care Practice',
    heroDescription: 'Attract more patients for LASIK, cataract surgery, and comprehensive eye care. Our marketing strategies address the unique procedural focus and insurance dynamics of ophthalmology practices.',
    primaryKeyword: 'ophthalmology marketing',
    secondaryKeywords: ['eye care marketing', 'eye doctor advertising', 'LASIK marketing'],
    accentColor: 'cyan',
    icon: '👁️',
    challenges: [
      { title: 'Procedural Focus', description: 'LASIK, cataract surgery, and other procedures require targeted campaigns with different patient journeys for each.' },
      { title: 'Insurance vs. Elective Split', description: 'Cataract surgery is insurance-covered while LASIK is elective. Marketing must address both audiences differently.' },
      { title: 'Patient Education Needs', description: 'Patients have many questions about eye procedures. Educational content builds confidence and drives consultations.' },
      { title: 'Referral Relationship Management', description: 'Optometrist referrals are a key patient source. B2B marketing to referring doctors complements patient-facing campaigns.' },
      { title: 'Aging Patient Demographics', description: 'Cataract and glaucoma patients skew older. Marketing must reach this demographic through appropriate channels.' },
    ],
    services: [
      { slug: 'google-ads', label: 'Google Ads' },
      { slug: 'seo-local-search', label: 'SEO & Local Search' },
      { slug: 'content-copywriting', label: 'Content & Copywriting' },
      { slug: 'email-drip-campaigns', label: 'Email Campaigns' },
      { slug: 'website-design-dev', label: 'Website Design' },
    ],
    whyUs: [
      { title: 'Procedure-Specific Campaigns', description: 'Separate marketing strategies for LASIK, cataracts, glaucoma, and comprehensive eye exams — each with targeted keywords and landing pages.' },
      { title: 'Insurance + Elective Dual Strategy', description: 'We market insurance-covered procedures and cash-pay elective procedures with completely different messaging and targeting.' },
      { title: 'Educational Funnel Design', description: 'Blog content, video explainers, and downloadable guides that educate patients and move them from research to consultation.' },
      { title: 'Patient Communication Automation', description: 'Pre-op and post-op email/SMS sequences that improve patient experience and reduce no-shows.' },
    ],
    stats: [
      { value: '190%', label: 'Increase in LASIK enquiries' },
      { value: '$42', label: 'Cost per LASIK consultation lead' },
      { value: '35%', label: 'Increase in cataract referrals' },
      { value: '#1', label: 'Local ranking for eye doctor keywords' },
    ],
    faqs: [
      { q: 'How do I market LASIK effectively?', a: 'LASIK marketing requires addressing fear and misconceptions. We create educational content (videos, blog posts, FAQs), run Google Ads targeting "LASIK near me" and "LASIK cost" keywords, and build landing pages with virtual consultation options. Social proof (patient video testimonials) is particularly effective.' },
      { q: 'How do I attract more cataract surgery patients?', a: 'Cataract patients are typically referred by optometrists and discovered through "cataract surgery near me" searches. We optimise both channels: building referral marketing programs for ODs and running SEO/Google Ads campaigns targeting cataract keywords for the 55+ demographic.' },
      { q: 'What digital marketing works for eye doctors?', a: 'SEO and Google Ads are the primary channels, targeting procedure-specific and symptom-based keywords. Educational content (blog articles on eye conditions) drives organic traffic. Email campaigns nurture leads and remind patients about annual exams. Facebook Ads reach the 50+ demographic effectively.' },
      { q: 'How do I market premium IOLs?', a: 'Premium IOLs (multifocal, toric) are an upgrade sale during cataract consultations. We create patient education materials, dedicated landing pages, and pre-consultation email sequences that inform patients about premium options before they arrive, increasing upgrade conversion rates.' },
    ],
    relatedIndustries: [
      { slug: 'dermatology', label: 'Dermatology Marketing' },
      { slug: 'plastic-surgery', label: 'Plastic Surgery Marketing' },
      { slug: 'primary-care', label: 'Primary Care Marketing' },
    ],
  },
  {
    slug: 'dermatology',
    title: 'Dermatology Marketing — Medical & Cosmetic Patient Growth | NextGen Health',
    metaDescription: 'Marketing for dermatology practices. Attract medical and cosmetic dermatology patients with SEO, ads, and social media.',
    h1: 'Dermatology Marketing — Attract Medical & Cosmetic Patients',
    heroDescription: 'Grow both sides of your dermatology practice — medical and cosmetic. Our dual-strategy approach ensures you attract insurance patients for medical dermatology and cash-pay patients for aesthetic services.',
    primaryKeyword: 'dermatology marketing',
    secondaryKeywords: ['dermatologist advertising', 'dermatology SEO', 'cosmetic dermatology marketing'],
    accentColor: 'amber',
    icon: '🔬',
    challenges: [
      { title: 'Medical vs. Cosmetic Patient Mix', description: 'Medical dermatology (insurance) and cosmetic dermatology (cash-pay) require fundamentally different marketing approaches.' },
      { title: 'Visual Results Marketing', description: 'Cosmetic dermatology patients want to see results. Before/after content is essential but must be compliant.' },
      { title: 'Insurance/Cash Pay Split', description: 'Balancing marketing investment between insurance-covered medical visits and higher-revenue cosmetic procedures.' },
      { title: 'Long Wait Lists', description: 'Some dermatology sub-specialties have long wait times. Marketing must manage expectations while maintaining demand.' },
      { title: 'Condition-Specific Search', description: 'Patients search by condition (acne, psoriasis, eczema), not specialty. SEO must target hundreds of condition keywords.' },
    ],
    services: [
      { slug: 'seo-local-search', label: 'SEO & Local Search' },
      { slug: 'google-ads', label: 'Google Ads' },
      { slug: 'social-media-marketing', label: 'Social Media Marketing' },
      { slug: 'meta-ads', label: 'Meta Ads' },
      { slug: 'content-copywriting', label: 'Content & Copywriting' },
    ],
    whyUs: [
      { title: 'Dual Medical/Cosmetic Strategy', description: 'Separate campaigns for medical dermatology (condition-based SEO) and cosmetic dermatology (social media + Meta Ads + visual content).' },
      { title: 'Condition-Specific Content', description: 'Comprehensive content for acne, psoriasis, eczema, skin cancer, and dozens of other conditions that drives organic patient enquiries.' },
      { title: 'Cosmetic Lead Nurturing', description: 'Automated email and SMS sequences for cosmetic services (Botox, fillers, laser) that convert enquiries into appointments.' },
      { title: 'Provider-to-Referral Marketing', description: 'B2B marketing to primary care physicians and other referring providers that drives medical dermatology referrals.' },
    ],
    stats: [
      { value: '240%', label: 'Increase in cosmetic enquiries' },
      { value: '$28', label: 'Average cost per new patient' },
      { value: '55%', label: 'Growth in organic traffic' },
      { value: '4.8★', label: 'Average Google rating achieved' },
    ],
    faqs: [
      { q: 'How do I market both medical and cosmetic dermatology?', a: 'Treat them as two separate marketing verticals. Medical dermatology: SEO and Google Ads targeting condition-based searches (acne treatment, dermatologist near me) with insurance messaging. Cosmetic dermatology: Instagram, Meta Ads, and visual content showcasing results (Botox, fillers, lasers) targeting cash-pay patients.' },
      { q: 'What is the best marketing for a new dermatology practice?', a: 'Start with Google Business Profile optimisation and Google Ads for immediate visibility. Build SEO with condition-specific blog content. Launch Instagram for cosmetic services. Within 6 months, you should have a steady organic pipeline supplemented by paid campaigns.' },
      { q: 'How do I attract Botox and filler patients?', a: 'Instagram and Facebook Ads are the primary channels. Share before/after content (within compliance), patient testimonials, and educational content about treatments. Google Ads targeting "Botox near me" captures high-intent searches. Special promotions and membership programs drive recurring bookings.' },
      { q: 'How much should a dermatology practice spend on marketing?', a: 'Typically 5-10% of revenue. Practices with a significant cosmetic component should invest more in social media and paid social. A practice generating $100K/month should invest $5K-$10K in marketing across SEO, Google Ads, social media, and content creation.' },
    ],
    relatedIndustries: [
      { slug: 'medspa', label: 'Medspa Marketing' },
      { slug: 'plastic-surgery', label: 'Plastic Surgery Marketing' },
      { slug: 'ophthalmology', label: 'Ophthalmology Marketing' },
    ],
  },
];

export function getIndustryBySlug(slug: string): IndustryData | undefined {
  return industries.find((i) => i.slug === slug);
}

export function getAllIndustrySlugs(): string[] {
  return industries.map((i) => i.slug);
}
