import { NextRequest, NextResponse } from 'next/server';
import jwt from 'jsonwebtoken';

function getJwtSecret(): string {
  const secret = process.env.JWT_SECRET;
  if (!secret) throw new Error('JWT_SECRET is not set.');
  return secret;
}

/**
 * Accepts a JWT token (generated by the OAuth callback popup) and sets it
 * as an httpOnly cookie in the caller's browsing context.
 *
 * This exists because modern browsers may block Set-Cookie from a popup
 * window that went through a third-party redirect chain (Google OAuth).
 * By having the *main* window call this endpoint, the cookie is set in
 * a first-party context and is always available.
 */
export async function POST(req: NextRequest) {
  try {
    const { token } = await req.json();
    if (!token) {
      return NextResponse.json({ error: 'Missing token' }, { status: 400 });
    }

    // Verify the token is valid before setting it as a cookie
    jwt.verify(token, getJwtSecret());

    const response = NextResponse.json({ success: true });
    response.cookies.set('auth_token', token, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      maxAge: 60 * 60 * 24 * 7, // 7 days
      path: '/',
    });

    return response;
  } catch (error) {
    console.error('Token login error:', error);
    return NextResponse.json({ error: 'Invalid token' }, { status: 401 });
  }
}
